apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nfs-home-webhook
  namespace: nfs-home-system
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nfs-home-webhook
  namespace: nfs-home-system
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: nfs-home-webhook:latest
  triggers:
    - type: ConfigChange
